trigger:
  branches:
    include:
      - main
  paths:
    include:
      - arm/*
      - azure-pipelines-infra.yml

variables:
  vmImageName: 'ubuntu-latest'
  docsContianerName: 'documents'
  deploymentTemplate: 'env-vnet-integration.bicep'

stages:
- stage: Infrastructure
  displayName: 'Deploy Infrastructure'

  jobs:
  - job: Deploy
    displayName: Deploy Azure Services
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: AzureCLI@2
      displayName: Create Resource Group
      inputs:
        azureSubscription: 'azure-knowledge-mining-arm-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az group create -l $(LOCATION) -n $(RESOURCEGROUP)'
        workingDirectory: '$(System.DefaultWorkingDirectory)/arm'

    - task: AzureCLI@2
      displayName: 'Deploy Environment'
      inputs:
        azureSubscription: 'azure-knowledge-mining-arm-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az deployment group create -g $(RESOURCEGROUP) --template-file $(deploymentTemplate) --parameters docsContainerName=$(docsContianerName) spnObjectId=$(spnObjectId)'
        workingDirectory: '$(System.DefaultWorkingDirectory)/arm'
